spring:
  application:
    name: pharma
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /pharma

logging:
  level:
    com.sanofi: INFO
    root: INFO
  file:
    name: logs/pharma.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{36} - %msg%n"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sanofi.common.entity
  configuration:
    map-underscore-to-camel-case: true