spring:
  config:
    activate:
      on-profile: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.130:3306/pharma_pro?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: pro_user
    password: Pro123456.
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 30000
  data:
    redis:
      host: localhost
      port: 6379
      password: 123654
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 32
          max-idle: 32
          min-idle: 4
          max-wait: -1ms
        shutdown-timeout: 200ms